# Generated by Django 4.1.7 on 2023-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2083)),
                ('doc_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
